nelmio_api_doc:
    documentation:
        info:
            title: BileMo
            description: Ceci est l'application BileMo! Récupérer les informations de vos client et sur les différents téléphones que nous vendons!
            version: 1.0.0
        securityDefinitions:
            Bearer:
                type: apiKey
                description: 'Value: Bearer {jwt}'
                name: Authorization
                in: Bearer Token
            security:
                -   Bearer: []
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
    models:
        names:
            - { alias: PhonesList , type: App\Entity\Phone , groups: [phones_list]}
            - { alias: PhoneShow , type: App\Entity\Phone , groups: [phone_show]}
            - { alias: BrandInPhoneShow , type: App\Entity\Brand , groups: [phone_show]}
            - { alias: BrandInPhoneslist , type: App\Entity\Brand , groups: [phones_list]}
            - { alias: CustomersList , type: App\Entity\Customer , groups: [customers_list]}
            - { alias: CustomerShow , type: App\Entity\Customer , groups: [customer_show]}
            - { alias: UserInCustomerShow , type: App\Entity\User , groups: [customer_show]}
            - { alias: UserInCustomerAfterCreation , type: App\Entity\User , groups: [after_creation]}
            - { alias: CustomerAfterCreation , type: App\Entity\Customer , groups: [after_creation]}
            - { alias: CustomerCreate , type: App\Entity\Customer , groups: [Create]}
