nelmio_api_doc:
    documentation:
        info:
            title: BileMo
            description: Ceci est l'application BileMo! Récupérer les informations de vos client et sur les différents téléphones que nous vendons!
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
